name: GASPOL
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        go: [1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.20]
        flag: [aa, ab, ac, ad, ae, af, ag, ah, ai, aj]
    timeout-minutes: 360
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Build
      run: |
          echo "1"
